INSERT INTO PROJETO_PERIODO.USUARIO (USUARIO_NOME, USUARIO_SOBRENOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_EMAIL, ULTIMA_ALTERACAO, SENHA_EXPIRADA)
VALUES('admin', 'admin', 'admin', 'f6fdffe48c908debf4c3bd36c32e72', 'emgs@a.recife.ifpe.edu.br', current_timestamp(), 0  );

INSERT INTO PROJETO_PERIODO.USUARIO (USUARIO_NOME, USUARIO_SOBRENOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_EMAIL, ULTIMA_ALTERACAO, SENHA_EXPIRADA)
VALUES('Renata', 'Freire', 'renata', 'f6fdffe48c908debf4c3bd36c32e72', 'renatafreire@recife.ifpe.edu.br', current_timestamp(), 0  );

INSERT INTO PROJETO_PERIODO.USUARIO (USUARIO_NOME, USUARIO_SOBRENOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_EMAIL, ULTIMA_ALTERACAO, SENHA_EXPIRADA)
VALUES('Ramide', 'Dantas', 'ramide', 'f6fdffe48c908debf4c3bd36c32e72', 'ramidedantas@recife.ifpe.edu.br', current_timestamp(), 0  );


INSERT INTO PROJETO_PERIODO.PERIODO (PERIODO_ANO, SEMESTRE)
VALUES (2015, 'SEGUNDO');

INSERT INTO PROJETO_PERIODO.CURSO (GRAU, CURSO_DS)
VALUES ('SUPERIOR', 'Análise de Sistemas');

INSERT INTO PROJETO_PERIODO.ALUNO (ALUNO_ID, ALUNO_MATRICULA, CURSO_ID)
VALUES( (SELECT USUARIO_ID  FROM USUARIO
        WHERE USUARIO_LOGIN LIKE 'admin'), 
        '20141Y6-RC0323', 
        (SELECT CURSO_ID FROM CURSO
         WHERE CURSO_DS LIKE 'Análise de Sistemas') );
         
INSERT INTO PROJETO_PERIODO.PROFESSOR (PROFESSOR_ID, PROFESSOR_SIAPE)
VALUES( (SELECT USUARIO_ID FROM USUARIO WHERE USUARIO_NOME LIKE 'Ramide'), '1428475');

INSERT INTO PROJETO_PERIODO.PROFESSOR (PROFESSOR_ID, PROFESSOR_SIAPE)
VALUES( (SELECT USUARIO_ID FROM USUARIO WHERE USUARIO_NOME LIKE 'Renata'), '1428476');

INSERT INTO PROJETO_PERIODO.DISCIPLINA (DISCIPLINA_DS, PROFESSOR_ID, CURSO_ID)
SELECT 'Padrões de Projeto',
(SELECT PROFESSOR_ID FROM PROFESSOR WHERE PROFESSOR_SIAPE LIKE '1428476'),
(SELECT CURSO_ID FROM CURSO WHERE CURSO_DS LIKE 'Análise de Sistemas') 
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM DISCIPLINA
WHERE DISCIPLINA_DS = 'Padrões de Projeto');

INSERT INTO PROJETO_PERIODO.DISCIPLINA (DISCIPLINA_DS, PROFESSOR_ID, CURSO_ID)
SELECT 'Desenvolvimento Web 2',
(SELECT PROFESSOR_ID FROM PROFESSOR WHERE PROFESSOR_SIAPE LIKE '1428475'),
(SELECT CURSO_ID FROM CURSO WHERE CURSO_DS LIKE 'Análise de Sistemas') 
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM DISCIPLINA
WHERE DISCIPLINA_DS = 'Desenvolvimento Web 2');

INSERT INTO PROJETO_PERIODO.DISCIPLINA_ALUNO 
VALUES ( (SELECT ALUNO_ID FROM ALUNO
          WHERE ALUNO_MATRICULA LIKE'20141Y6-RC0323' ),
		 ( SELECT DISCIPLINA_ID FROM DISCIPLINA
		   WHERE DISCIPLINA_DS LIKE 'Padrões de Projeto'), current_timestamp() );
