DROP DATABASE IF EXISTS PROJETO_PERIODO;
CREATE DATABASE PROJETO_PERIODO;
USE PROJETO_PERIODO;
DROP TABLE IF EXISTS PROJETO_PERIODO.USUARIO;
CREATE TABLE PROJETO_PERIODO.USUARIO (
	USUARIO_NOME VARCHAR(200),
	USUARIO_LOGIN VARCHAR(20),
	USUARIO_SENHA VARCHAR(20),
	USUARIO_EMAIL VARCHAR(50),
	PRIMARY KEY(USUARIO_LOGIN)
);


DROP TABLE IF EXISTS PROJETO_PERIODO.CURSO;
CREATE TABLE PROJETO_PERIODO.CURSO (
	GRAU ENUM('SUPERIOR', 'TECNICO'),	
	CURSO_DS VARCHAR(20),
	PRIMARY KEY(CURSO_DS)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.DISCIPLINA;
CREATE TABLE PROJETO_PERIODO.DISCIPLINA ( 
	DISCIPLINA_CD INT NOT NULL AUTO_INCREMENT,
	DISCIPLINA_DS varchar(20),
	CURSO_DS VARCHAR(20),
	PRIMARY KEY(DISCIPLINA_CD),
	FOREIGN KEY (CURSO_DS) REFERENCES CURSO(CURSO_DS)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.DEPARTAMENTO;
CREATE TABLE PROJETO_PERIODO.DEPARTAMENTO ( 
	DEPARTAMENTO_DS VARCHAR(50),
	PRIMARY KEY(DEPARTAMENTO_DS)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.ORIENTADOR;
CREATE TABLE PROJETO_PERIODO.ORIENTADOR( 
	ORIENTADOR_NOME VARCHAR(200),
	ORIENTADOR_SIAPE VARCHAR(20),
	DISCIPLINA_CD INT,
	PRIMARY KEY(ORIENTADOR_SIAPE),
	FOREIGN KEY(DISCIPLINA_CD) REFERENCES DISCIPLINA(DISCIPLINA_CD)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.FUNCIONARIO;
CREATE TABLE PROJETO_PERIODO.FUNCIONARIO ( 
	USUARIO_LOGIN VARCHAR(20),
	FUNCIONARIO_SIAPE VARCHAR(20),
	DEPARTAMENTO_DS VARCHAR(50),
	PRIMARY KEY(FUNCIONARIO_SIAPE),
	FOREIGN KEY (DEPARTAMENTO_DS) REFERENCES DEPARTAMENTO(DEPARTAMENTO_DS),
	FOREIGN KEY (USUARIO_LOGIN) REFERENCES USUARIO(USUARIO_LOGIN)
);


DROP TABLE IF EXISTS PROJETO_PERIODO.ALUNO;
CREATE TABLE PROJETO_PERIODO.ALUNO (
	USUARIO_LOGIN VARCHAR(20),
	ALUNO_MATRICULA VARCHAR(20),
	CURSO_DS VARCHAR(20),
	PRIMARY KEY (ALUNO_MATRICULA),
	FOREIGN KEY (CURSO_DS) REFERENCES PROJETO_PERIODO.CURSO(CURSO_DS),
	FOREIGN KEY (USUARIO_LOGIN) REFERENCES PROJETO_PERIODO.USUARIO(USUARIO_LOGIN)
);


DROP TABLE IF EXISTS PROJETO_PERIODO.DISCIPLINA_ALUNO;
CREATE TABLE PROJETO_PERIODO.DISCIPLINA_ALUNO ( 
	ALUNO_MATRICULA VARCHAR(20),
	DISCIPLINA_CD INT,
	PRIMARY KEY (ALUNO_MATRICULA, DISCIPLINA_CD),
	FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(ALUNO_MATRICULA),
	FOREIGN KEY (DISCIPLINA_CD) REFERENCES DISCIPLINA(DISCIPLINA_CD)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.MONITOR;
CREATE TABLE PROJETO_PERIODO.MONITOR ( 
	MONITOR_CD INT NOT NULL AUTO_INCREMENT,
	ALUNO_MATRICULA VARCHAR(20),
	MODALIDADE ENUM('MONITOR', 'VOLUNTARIO'),
	DISCIPLINA_CD INT,
	PRIMARY KEY(MONITOR_CD),
	FOREIGN KEY(ALUNO_MATRICULA) REFERENCES ALUNO(ALUNO_MATRICULA),
	FOREIGN KEY(DISCIPLINA_CD) REFERENCES DISCIPLINA(DISCIPLINA_CD)
);



DROP TABLE IF EXISTS PROJETO_PERIODO.RELATORIO_FREQUENCIA;
CREATE TABLE PROJETO_PERIODO.RELATORIO_FREQUENCIA (
	RELATORIO_CD INT NOT NULL AUTO_INCREMENT,
	RELATORIO_ANO int(4),
	RELATORIO_MES int(2),
	RELATORIO_CARGA_HORARIA INT(2),
	MONITOR_CD INT,
	RELATORIO_EDITAL VARCHAR(6),
	ORIENTADOR_SIAPE VARCHAR(20),
	FUNCIONARIO_SIAPE VARCHAR(20),
	DATA_ENTREGA DATE,
	PRIMARY KEY (RELATORIO_CD),
	FOREIGN KEY (ORIENTADOR_SIAPE) REFERENCES ORIENTADOR(ORIENTADOR_SIAPE),
	FOREIGN KEY (FUNCIONARIO_SIAPE) REFERENCES FUNCIONARIO(FUNCIONARIO_SIAPE),
    FOREIGN KEY (MONITOR_CD) REFERENCES MONITOR(MONITOR_CD)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.SEMANA;
CREATE TABLE PROJETO_PERIODO.SEMANA(
	SEMANA_CD INT NOT NULL AUTO_INCREMENT,
	SEMANA_DESCRICAO VARCHAR(200),
	SEMANA_OBS VARCHAR(200),
	RELATORIO_CD INT,
	PRIMARY KEY(SEMANA_CD),
	FOREIGN KEY (RELATORIO_CD) REFERENCES RELATORIO_FREQUENCIA(RELATORIO_CD)
);

DROP TABLE IF EXISTS PROJETO_PERIODO.ATIVIDADE;
CREATE TABLE PROJETO_PERIODO.ATIVIDADE (
	ATIVIDADE_CD INT NOT NULL AUTO_INCREMENT,
	ATIVIDADE_DATA DATE,
	HORARIO_ENTRADA TIMESTAMP,
	HORARIO_SAIDA TIMESTAMP,
	SEMANA_CD INT,
	PRIMARY KEY(ATIVIDADE_CD),
	FOREIGN KEY (SEMANA_CD) REFERENCES SEMANA(SEMANA_CD)
);

