DROP USER "PROJETO_PERIODO" CASCADE;
-- USER SQL
CREATE USER PROJETO_PERIODO IDENTIFIED BY PROJETO_PERIODO 
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
-- SYSTEM PRIVILEGES
GRANT "DBA" TO PROJETO_PERIODO ;

----------------------------- Usuario --------------------------------- 

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."USUARIO" (
	USUARIO_ID NUMBER,
	USUARIO_NOME VARCHAR2(200),
	USUARIO_SOBRENOME VARCHAR2(200),
	USUARIO_LOGIN VARCHAR2(20),
	USUARIO_SENHA VARCHAR2(40),
	USUARIO_EMAIL VARCHAR2(50),
	ULTIMO_ACESSO TIMESTAMP,
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(USUARIO_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.USUARIO_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.USUARIO
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USUARIO_ID IS NULL THEN
      SELECT SQ_USUARIO.NEXTVAL INTO :NEW.USUARIO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


----------------------------- Periodo ---------------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_PERIODO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."PERIODO" (
	PERIODO_ID NUMBER NOT NULL,
	PERIODO_ANO NUMBER NOT NULL,
    SEMESTRE VARCHAR2(10) CHECK( SEMESTRE IN ('PRIMEIRO','SEGUNDO') ) NOT NULL,
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(PERIODO_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.PERIODO_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.PERIODO
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PERIODO_ID IS NULL THEN
      SELECT SQ_PERIODO.NEXTVAL INTO :NEW.PERIODO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


----------------------------- Curso ---------------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_CURSO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."CURSO" (
	CURSO_ID NUMBER NOT NULL,
	GRAU VARCHAR2(10) CHECK( GRAU IN ('SUPERIOR','TECNICO') ) NOT NULL,
	CURSO_DS VARCHAR2(20) NOT NULL,
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(CURSO_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.CURSO_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.CURSO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CURSO_ID IS NULL THEN
      SELECT SQ_CURSO.NEXTVAL INTO :NEW.CURSO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

----------------------------- Professor ---------------------------------

CREATE TABLE "PROJETO_PERIODO"."PROFESSOR"( 
	PROFESSOR_ID NUMBER,
	PRIMARY KEY(PROFESSOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (PROFESSOR_ID) REFERENCES "PROJETO_PERIODO"."USUARIO"(USUARIO_ID)
);

----------------------------- Disciplina ---------------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_DISCIPLINA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."DISCIPLINA" ( 
	DISCIPLINA_ID NUMBER NOT NULL,
	PROFESSOR_ID NUMBER,
	DISCIPLINA_DS VARCHAR2(200),
	CURSO_ID NUMBER NOT NULL,
	PRIMARY KEY(DISCIPLINA_ID),
	FOREIGN KEY (PROFESSOR_ID) REFERENCES "PROJETO_PERIODO"."PROFESSOR"(PROFESSOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (CURSO_ID) REFERENCES "PROJETO_PERIODO"."CURSO"(CURSO_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.DISCIPLINA_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.DISCIPLINA
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DISCIPLINA_ID IS NULL THEN
      SELECT SQ_DISCIPLINA.NEXTVAL INTO :NEW.DISCIPLINA_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

------------------------------ Aluno -------------------------------

CREATE TABLE "PROJETO_PERIODO"."ALUNO" (
	ALUNO_ID NUMBER NOT NULL,
	ALUNO_MATRICULA VARCHAR2(20) NOT NULL,
	CURSO_ID NUMBER NOT NULL,
	PRIMARY KEY (ALUNO_ID),
	FOREIGN KEY (CURSO_ID) REFERENCES "PROJETO_PERIODO"."CURSO"(CURSO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (ALUNO_ID) REFERENCES "PROJETO_PERIODO"."USUARIO"(USUARIO_ID)
);

CREATE TABLE "PROJETO_PERIODO"."DISCIPLINA_ALUNO" ( 
	ALUNO_ID NUMBER NOT NULL,
	DISCIPLINA_ID NUMBER NOT NULL,
	PRIMARY KEY (ALUNO_ID, DISCIPLINA_ID),
	FOREIGN KEY (ALUNO_ID) REFERENCES "PROJETO_PERIODO"."ALUNO"(ALUNO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (DISCIPLINA_ID) REFERENCES "PROJETO_PERIODO"."DISCIPLINA"(DISCIPLINA_ID)
);

------------------------------ Monitoria -------------------------------

CREATE TABLE "PROJETO_PERIODO"."MONITORIA" ( 
	MONITOR_ID NUMBER NOT NULL,
	ALUNO_ID NUMBER NOT NULL,
	MODALIDADE VARCHAR2(10) CHECK( MODALIDADE IN ('BOLSISTA','VOLUNTARIO') ) NOT NULL,
	DISCIPLINA_ID INT NOT NULL,
	PERIODO_ID NUMBER NOT NULL,
	HABILITADO CHAR CHECK (HABILITADO in (0,1)) NOT NULL,
	HORARIO_ENTRADA VARCHAR(5),
	HORARIO_SAIDA VARCHAR2(5),
	PRIMARY KEY(MONITOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY(ALUNO_ID) REFERENCES "PROJETO_PERIODO"."ALUNO"(ALUNO_ID),
	FOREIGN KEY(PERIODO_ID) REFERENCES "PROJETO_PERIODO"."PERIODO"(PERIODO_ID),
	FOREIGN KEY(DISCIPLINA_ID) REFERENCES "PROJETO_PERIODO"."DISCIPLINA"(DISCIPLINA_ID)
);


-------------------------- Relatório Frequência -------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_RELATORIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."RELATORIO_FREQUENCIA" (
	RELATORIO_ID NUMBER NOT NULL,
	RELATORIO_MES NUMBER(2),
	MONITOR_ID NUMBER NOT NULL,
	SITUACAO_RELATORIO VARCHAR2(10) CHECK( SITUACAO_RELATORIO IN ('APROVADO','ESPERA') ) NOT NULL,
	PRIMARY KEY (RELATORIO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (MONITOR_ID) REFERENCES "PROJETO_PERIODO"."MONITORIA"(MONITOR_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.RELATORIO_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.RELATORIO_FREQUENCIA
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RELATORIO_ID IS NULL THEN
      SELECT SQ_RELATORIO.NEXTVAL INTO :NEW.RELATORIO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

-------------------------------- Semana -----------------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_SEMANA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."SEMANA"(
	SEMANA_ID NUMBER NOT NULL,
	SEMANA_DESCRICAO VARCHAR2(200),
	SEMANA_OBS VARCHAR2(200),
	RELATORIO_ID NUMBER,
	PRIMARY KEY(SEMANA_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (RELATORIO_ID) REFERENCES "PROJETO_PERIODO"."RELATORIO_FREQUENCIA"(RELATORIO_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.SEMANA_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.SEMANA
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SEMANA_ID IS NULL THEN
      SELECT SQ_SEMANA.NEXTVAL INTO :NEW.SEMANA_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

----------------------------- Atividade ---------------------------

CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_ATIVIDADE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."ATIVIDADE" (
	ATIVIDADE_ID NUMBER NOT NULL,
	ATIVIDADE_DATA DATE,
	HORARIO_ENTRADA VARCHAR2(5),
	HORARIO_SAIDA VARCHAR2(5),
	SEMANA_ID NUMBER,
	PRIMARY KEY(ATIVIDADE_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (SEMANA_ID) REFERENCES "PROJETO_PERIODO"."SEMANA"(SEMANA_ID)
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.ATIVIDADE_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.ATIVIDADE
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ATIVIDADE_ID IS NULL THEN
      SELECT SQ_ATIVIDADE.NEXTVAL INTO :NEW.ATIVIDADE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


----------------------------- Documento ---------------------------------


CREATE SEQUENCE  "PROJETO_PERIODO"."SQ_TEMPLATE_DOCUMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "PROJETO_PERIODO"."TEMPLATE_DOCUMENTO" (
   TEMPLATE_ID NUMBER NOT NULL,
   TEMPLATE_CONTENT BLOB,
   TEMPLATE_NOME VARCHAR2(30),
   PRIMARY KEY(TEMPLATE_ID),
   ULTIMA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER PROJETO_PERIODO.DOCUMENTO_AUTO_INCREMENTO
BEFORE INSERT ON PROJETO_PERIODO.TEMPLATE_DOCUMENTO
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TEMPLATE_ID IS NULL THEN
      SELECT SQ_TEMPLATE_DOCUMENTO.NEXTVAL INTO :NEW.TEMPLATE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

-----------------------------------------------------------------

COMMIT;
