INSERT INTO PROJETO_PERIODO.USUARIO (USUARIO_NOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_EMAIL, ULTIMA_ALTERACAO)
VALUES('admin', 'admin', 'f6fdffe48c908debf4c3bd36c32e72', 'emgs@a.recife.ifpe.com.br', current_timestamp()  );

INSERT INTO PROJETO_PERIODO.USUARIO (USUARIO_NOME, USUARIO_LOGIN, USUARIO_SENHA, USUARIO_EMAIL, ULTIMA_ALTERACAO)
VALUES('Paulo', 'FUNCIONARIOLOGIN', 'cc7a84634199040d54376793842fe035', 'funcionario@recife.ifpe.com.br', current_timestamp()  );

INSERT INTO PROJETO_PERIODO.CURSO (GRAU, CURSO_DS)
VALUES ('SUPERIOR', 'Análise de Sistemas');

INSERT INTO PROJETO_PERIODO.ALUNO (ALUNO_ID, ALUNO_MATRICULA, CURSO_ID)
VALUES( (SELECT USUARIO_ID  FROM USUARIO
        WHERE USUARIO_LOGIN LIKE 'admin'), 
        '20141Y6-RC0323', 
        (SELECT CURSO_ID FROM CURSO
         WHERE CURSO_DS LIKE 'Análise de Sistemas') );

INSERT INTO PROJETO_PERIODO.DISCIPLINA (DISCIPLINA_DS, CURSO_ID)
SELECT 'Padrões de Projeto', (SELECT CURSO_ID FROM CURSO WHERE CURSO_DS LIKE 'Análise de Sistemas') 
FROM DUAL
WHERE NOT EXISTS (SELECT * FROM DISCIPLINA
WHERE DISCIPLINA_DS = 'Padrões de Projeto');

INSERT INTO PROJETO_PERIODO.DISCIPLINA_ALUNO 
VALUES ( (SELECT ALUNO_ID FROM ALUNO
          WHERE ALUNO_MATRICULA LIKE'20141Y6-RC0323' ),
		 ( SELECT DISCIPLINA_ID FROM DISCIPLINA
		   WHERE DISCIPLINA_DS LIKE 'Padrões de Projeto') );
		   
INSERT INTO PROJETO_PERIODO.ORIENTADOR (ORIENTADOR_NOME, ORIENTADOR_SIAPE, DISCIPLINA_ID)
VALUES('Roberto', '1428475', 
(SELECT DISCIPLINA_ID FROM DISCIPLINA
 WHERE DISCIPLINA_DS = 'Padrões de Projeto') );
 
INSERT INTO PROJETO_PERIODO.MONITOR (MONITOR_ID, MODALIDADE, DISCIPLINA_ID)
VALUES( (SELECT ALUNO_ID FROM ALUNO
        WHERE ALUNO_MATRICULA LIKE '20141Y6-RC0323' ), 
       'BOLSISTA', 
      (SELECT DISCIPLINA_ID FROM DISCIPLINA
       WHERE DISCIPLINA_DS LIKE 'Padrões de Projeto') );

INSERT INTO PROJETO_PERIODO.DEPARTAMENTO 
(DEPARTAMENTO_DS, DEPARTAMENTO_DS_ABREV)
VALUES('Direção de Ensino', 'DEN');
	
INSERT INTO PROJETO_PERIODO.FUNCIONARIO
VALUES( (SELECT USUARIO_ID FROM USUARIO
        WHERE USUARIO_LOGIN LIKE 'FUNCIONARIOLOGIN'), 
       '5847560',
      (SELECT DEPARTAMENTO_ID FROM DEPARTAMENTO
       WHERE DEPARTAMENTO_DS_ABREV LIKE 'DEN'));